### ISSUE TITLE
be/todo - 수입 CRUD 구현

### ISSUE THREAD

**Issue by 021Skyfall** [kimtjrgus/salog#124]
## 설명
컨트롤러, 엔티티, 디티오, 매퍼, 레포, 서비스 로직 등 구현

*기본 구조 이후 이렇게 분리하고 할일에 기능 별로 적는 것이 직관적일 것이라 판단해서 수정합니다.

JPA 엔티티 간 연결은 다른 이슈로 분리

## 할일
1. [x] : Controller
   - 1. [x] : C 
   - 2. [x] : R
   - 3. [x] : U
   - 4. [x] : D
2. [x] : Dto
3. [x] : Entity
4. [x] : Mapper
5. [x] : Repository
6. [x] : Servicery
   - 1. [x] : C
   - 2. [x] : R
      - 1. [x] : 날짜 별 쿼리 작성
   - 3. [x] : U
   - 4. [x] : D

## 특이사항
1. 태그 관련 제외
2. 회원 관련 제외
3. 통계 관련은 통계 이슈에서 재작성

**Comment by kimtjrgus** [comment]
조회시 특정 일자 기준으로 리턴하는 것
 - 예를 들면 오늘날짜 기준 최근 50개항목 < 이거 맞을까요? 
 좋다고 생각합니다

**Comment by 021Skyfall** [comment]
아뇨 그게 아니라 지금은 아무 구분 없이 모든 수입을 전체 다 조회하게끔 되어있는데
이거를 예를 들어 2024-12-12 인것들, 2024-12-13 인것들 이런 식으로 날짜를 필수적으로 입력해야되는거 아닌가라는 말입니다.

**Comment by 021Skyfall** [comment]
회의 결과

API 파라미터 date 는 필수 / 월별 조회 → 일기 작성, 조회시 사용
→ date의 양식은 2023-12-00 형식
→ 캘린더에서 일자 클릭 시 형식은 2023-12-12 형식
일자가 00 이면 월별로 조회됨 / 일자에 01 형식으로 정확히 들어오면 해당 일자만 조회

로 변경
