### ISSUE TITLE
be/todo - 지출 CRUD 구현

### ISSUE THREAD

**Issue by kimtjrgus** [kimtjrgus/salog#125]
## 설명

지출에 대한 Service, Controller, Repository 를 작성한다.
Entity, DTO, Mapper는 앞서 기본 구조 작성 시 작성 완료
(태그 및 일기 로직 작성은 추후, 기본적인 지출기능만 작성)

## 할일

1. Controller 구현
>  - 1. [x] : C
>  - 2. [x] : R
>  - 3. [x] : U
>  - 4. [x] : D

2. Servcie 구현
>  -  1. [x] : C
>  -  2. [x] : R
>  -  3. [x] : U
>  -  4. [x] : D 

## 특이사항
- (0104 추가) DTO에 유효성 검사 추가
- (0103 추가) 일기와 매핑, 태그와 매핑  추후 구현 
그 외 구현 후 테스트 진행 중 

- > 태그테이블 작업이 겹치므로 수입태그 완료 후 지출 태그 구현 예정
(임시) 태그는 String값으로 저장하게 구현함.

- 통계 및 고정 관련로직도 추후 작성

(회의 후 추가)
API 파라미터 date 는 필수 / 월별 조회 → 일기 작성, 조회시 사용
→ date의 양식은 2023-12-00 형식
→ 캘린더에서 일자 클릭 시 형식은 2023-12-12 형식
일자가 00 이면 월별로 조회됨 / 일자에 01 형식으로 정확히 들어오면 해당 일자만 조회

**Comment by 021Skyfall** [comment]
가계부 태그 제가 해요?
